name: Deploy To AWS

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: clone the repo
        uses: actions/checkout@vi

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::771500531194:role/GithubActionSetUpRolestaging
          aws-region: us-east-2

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with: 
          working_dir: './cdk'
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
